name: CI - Build
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main
      - bugfix/*
      - hotfix/*
      - feature/*

permissions:
  contents: read
  pull-requests: write

jobs:
  buil-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure JDK17 and Cache
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Permissions Wrapper
        run: chmod +x gradlew

      - name: Compile
        run: ./gradlew build -x test

      - name: Execute test + jacoco
        run: ./gradlew test jacocoTestReport

      - name: Execute pitest
        run: ./gradlew pitest

      - name: Publish report test
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Result post test
          path: '**/build/test-results/test/*.xml'
          reporter: java-junit

      - name: Verificar token Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          if [ -z "$SONAR_TOKEN" ]; then
            echo "❌ SONAR_TOKEN está vacío"
          else
            echo "✅ SONAR_TOKEN tiene valor, longitud: ${#SONAR_TOKEN}"
          fi

      - name: Test token SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          curl -s -u $SONAR_TOKEN: \
            "https://sonarcloud.io/api/projects/search?projects=darwingpacheco_CreateUser_retoPragma&organization=darwingpacheco" \
            | python3 -c "import sys,json; d=json.load(sys.stdin); print('Proyecto encontrado:', d['paging']['total'] > 0)"

      - name: Analisis SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew sonar -Dsonar.qualitygate.wait=true